name: flake-supervolo
on:
  push:
    branches: [main, ci-test]
  pull_request:

jobs:
    sitl-bc:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
              with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: cachix/cachix-action@v15
              with:
                name: galois
            - run: nix build .#sitl_bc
            - uses: actions/upload-artifact@v4
              with:
                path: result/bc/bin
                name: supervolo-sitl-bitcode
