name: flake-supervolo
on:
  push:
    branches: [main, ci-test]
  pull_request:

jobs:
    sitl-bc:
        runs-on: ubuntu-24.04
        strategy:
          matrix:
            nix_target: ['sitl_bc', 'ardupilot_sitl_bc']
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
              with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: cachix/cachix-action@v15
              with:
                name: galois
                authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
            - run: nix build .#${{ matrix.nix_target }}
            - uses: actions/upload-artifact@v4
              with:
                if-no-files-found: error
                path: result/bc/bin
                name: ${{ matrix.nix_target }}-bitcode
